CREATE TABLE PERSON3 ( 
                    ID NUMBER(5),
                    NAME VARCHAR2(30)
                    );

ALTER TABLE PERSON3 ADD HP VARCHAR2(20);
ALTER TABLE PERSON3 RENAME COLUMN HP TO TEL;
ALTER TABLE PERSON3  MODIFY TEL VARCHAR2(13);
ALTER TABLE PERSON3 DROP COLUMN TEL;
DESC PERSON3;
SELECT * FROM PERSON3;
            
--p345
CREATE TABLE DEPT_SEQUENCE
    AS SELECT * FROM DEPT WHERE 1 != 1;
SELECT * FROM DEPT_SEQUENCE;

--시퀀스 만들기
CREATE SEQUENCE SEQ_DEPT_SEQUENCE
    INCREMENT BY 10
    START WITH 10
    MAXVALUE 90
    MINVALUE 0
    NOCYCLE
    CACHE 2;
    
INSERT INTO DEPT_SEQUENCE (DEPTNO, DNAME, LOC)
VALUES (seq_dept_sequence.nextval, 'DATABASE', 'SEOUL');

SELECT * FROM DEPT_SEQUENCE;

SELECT SEQ_DEPT_SEQUENCE.CURRVAL FROM DUAL;

ALTER SEQUENCE SEQ_DEPT_SEQUENCE
 INCREMENT BY 3
 MAXVALUE 99
 CYCLE;

CREATE TABLE TABLE_NOTNULL(
    LOGIN_ID VARCHAR2(20) NOT NULL,
    LOGIN_PWD VARCHAR2(20) NOT NULL,
    TEL     VARCHAR2(20)
);
SELECT * FROM TABLE_NOTNULL;

INSERT INTO TABLE_NOTNULL
VALUES ('ABCD', 'ABCD', '010-1234-5678');

--실습 14-6
CREATE TABLE TABLE_NOTNULL2(
    LOGOIN_ID VARCHAR2(20) CONSTRAINT AAA_MY_NOTNULL NOT NULL,
    LOGOIN_PWD VARCHAR2(20)CONSTRAINT AAA_MY_PWD_NOTNULL NOT NULL,
    TEL VARCHAR2(20)
);
SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
FROM USER_CONSTRAINTS;

--추가로 제약이 없는 컬럼에 제약(CONSTRAINT)를 줄 수 있다.
ALTER TABLE TABLE_NOTNULL2
MODIFY(TEL NOT NULL);
DESC TABLE_NOTNULL2;

ALTER TABLE TABLE_NOTNULL2
MODIFY(TEL NULL);
DESC TABLE_NOTNULL2;

ALTER TABLE TABLE_NOTNULL2
MODIFY(TEL CONSTRAINT AAA_MY_NOTNULL3 NOT NULL);

ALTER TABLE TABLE_NOTNULL2
DROP CONSTRAINT AAA_MY_NOTNULL3);

--실습 14-29
CREATE TABLE TABLE_TABLE_PK(
    LOGIN_ID VARCHAR2(20) PRIMARY KEY,
    LOGIN_PWD VARCHAR2(20) NOT NULL,
    TEL VARCHAR2(20)
);
DESC TABLE_TABLE_PK;
CREATE SEQUENCE PERSON
    INCREMENT BY 10
    START WITH 1
    MAXVALUE 90
    MINVALUE 0
    NOCYCLE
    CACHE 1;
SELECT * FROM PERSON;

DROP TABLE BUSINESSCARDS;

SELECT * FROM businesscards;

INSERT INTO BUSINESSCARDS
VALUES (seq_businesscards.nextval, '홍길동', '010-1111-1111', 'AAA@GMAIL.COM', '회사', '종로');
