--1. 오라클 처음 접속 후 hr 계정을 열려면 어떨게 해야하나요?
-- 1-1 관리자 계정 접속 쿼리 : (sqlplus system  서버셋팅 때 넣은 비밀번호 입력 ->smart123)
-- 1-2 연습용 계정 열기 쿼리 : (sqlplus hr tiger)

--2. 오라클 처음 접속 후 scott 계정을 만들고 비밀번호를 tiger로 하려면 어떻게 해야 하나요?
-- 2-1 scott 계정 만들고 비번 tiger 지정 쿼리 : (create user c##scott identified by c##tiger default tablespace users temporary tablespace temp;)
-- 2-2 scott 계정에 CONNECT,RESOURCE,UNLIMITED TABLESPACE 3가지 권한을 주는 쿼리 :(grant connect, resouce, unlimited, tablespace dba to scott;)

--3. Q1
SELECT * FROM EMP WHERE ENAME LIKE '%S';

--4. Q2
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO FROM EMP WHERE JOB = 'SALESMAN';

--5. Q3
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO FROM EMP WHERE DEPTNO > 10 AND SAL > 2000;
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO FROM EMP WHERE DEPTNO = 20 AND SAL > 2000
UNION
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO FROM EMP WHERE DEPTNO = 30 AND SAL > 2000;

--6. Q4
SELECT * FROM EMP WHERE NOT (SAL >= 2000 AND SAL <= 3000);

--7. Q5
SELECT ENAME, EMPNO, SAL ,DEPTNO FROM EMP WHERE ENAME LIKE '%E%' AND DEPTNO = 30 AND NOT (SAL >= 1000 AND SAL <=2000);

--8. Q6
SELECT * FROM EMP WHERE COMM IS NULL AND MGR IS NOT NULL AND JOB IN('MANAGER','CLERK') AND ENAME NOT LIKE '_L%';

--9. Q1
SELECT EMPNO, RPAD(SUBSTR(EMPNO, 1, 2), 4, '*') AS MASKING_EMPNO,ENAME, RPAD(SUBSTR(ENAME, 1, 1), 5, '*') AS MASKING_ENAME FROM EMP WHERE LENGTH(ENAME) = 5;

--10. Q2
SELECT EMPNO, ENAME, SAL, TRUNC(SAL/21.5,2) AS DAY_PAY, ROUND((SAL/21.5)/8, 1) AS TIME_PAY FROM EMP;

--11. Q3
SELECT EMPNO, ENAME, HIREDATE AS HIREDATE, NEXT_DAY(ADD_MONTHS(HIREDATE, 3), '월') AS "R_JOB", NVL2(COMM, TO_CHAR(COMM), 'N/A') FROM EMP;

--12. Q4
SELECT EMPNO, ENAME, MGR,
CASE 
WHEN SUBSTR(MGR,1, 2) IS NULL THEN '0000'
WHEN SUBSTR(MGR,1, 2) = 75 THEN '5555'
WHEN SUBSTR(MGR,1, 2) = 76 THEN '6666'
WHEN SUBSTR(MGR,1, 2) = 77 THEN '7777'
WHEN SUBSTR(MGR,1, 2) = 78 THEN '8888'
ELSE TO_CHAR(MGR)
END AS CHG_MGR
FROM EMP;

--13. Q1
SELECT DEPTNO, TRUNC(AVG(SAL)) AS AVG_SAL, MAX(SAL) AS MAX_SAL, MIN(SAL) AS MIN_SAL, COUNT(*) AS CNT FROM EMP GROUP BY DEPTNO;

--14. Q2
SELECT JOB, COUNT(*) FROM EMP GROUP BY JOB HAVING COUNT(JOB) >= 3;

--15. Q3
SELECT SUBSTR(HIREDATE, 1, 2) AS HIRE_YEAR, DEPTNO, COUNT(*) FROM EMP GROUP BY SUBSTR(HIREDATE, 1, 2), DEPTNO;

--16. Q4
SELECT NVL2(COMM, 'O', 'X'), COUNT(*) FROM EMP GROUP BY NVL2(COMM, 'O', 'X');

--17. Q1
SELECT DEPTNO, DNAME, EMPNO, ENAME, SAL FROM EMP E NATURAL JOIN DEPT D WHERE SAL > 2000 ORDER BY DEPTNO;

--18. Q2
SELECT DEPTNO, DNAME, TRUNC(AVG(SAL)) AS AVG_SAL, MAX(SAL) AS MAX_SAL, MIN(SAL) AS MIN_SAL, COUNT(*) AS CNT FROM EMP NATURAL JOIN DEPT GROUP BY DEPTNO, DNAME;

--19. Q3
SELECT DEPTNO, DNAME, EMPNO, ENAME, JOB, SAL FROM EMP NATURAL JOIN DEPT ORDER BY DEPTNO;

--20. Q1
SELECT JOB 
